pipeline {
    agent any
    stages {
        stage('write'){
            steps{
                script{
                    def get = new URL("https://httpbin.org/get").openConnection();
                    def getRC = get.getResponseCode();
                    println(getRC);
                    if(getRC.equals(200)) {
                            println(get.getInputStream().getText());
                        }else{
                        println("API call Failed !!!");
                        }
                    def date = new Date()
                    def data = "Hello World\nSecond line\n" + date
                    writeFile(file: 'zorg.xml', xml: data)
                    sh "ls -l"
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
    }
}
