pipeline {
    agent any
    stages {
        stage('write'){
            steps{
                script{
                    
                    def date = new Date()
                    def data = "<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">

<s:Body>

<Success xmlns="http://www.smashfly.com/services/simplepost/v2">true</Success>

</s:Body>

</s:Envelope>"
                    writeFile(file: 'zorg.xml', text: data)
                    sh "ls -l"
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
    }
}
